app = "testbot2"
primary_region = "ams"

[build]

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python main.py"

# Telegram botga HTTP port kerak emas.
# Shuning uchun [http_service] bo'limi bo'lmasa ham bo'ladi.