app = 'telegrambot1212'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  TZ = 'Asia/Tashkent'

[processes]
  app = 'python -u main.py'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256